apiVersion: v1
data:
  dbstring: cG9zdGdyZXM6Ly9hZG1pbjpiODRuZGRmdzByMzRobEByZHMtcG9zdGdyZXMtY2x1c3Rlci1mdmZkZGYuYW1hem9uYXdzLmNvbS9leGNoYW5nZWRi
kind: Secret
metadata:
  name: api-db-secret
  namespace: webapi-dev